spring:
  application:
    name: greeting-service

management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "parando"
  default-value: "Mondo!"
